"""
Tests for the weight-fitting script: the before/after split that keeps the
setlist signal from leaking into its own target, and the optimiser itself.
"""

import random
from datetime import date, timedelta

import pytest

from sources.models import Track
from train_weights import (
    FULL_FEATURES, LISTNET, RATIO, Group, build_groups, fit_grid, fit_sgd,
    normalized, project, simplex_grid,
)


def _track(name: str, released: str = '2020-01-01') -> Track:
    return Track(
        id=name, name=name, release_date=released, release_date_precision='day',
        duration_ms=200_000, album_id='a', album_name='Album',
    )


def _shows(start: date, setlists: list[set[str]], every_days: int = 3) -> list[tuple[date, set[str]]]:
    return [(start + timedelta(days=i * every_days), songs) for i, songs in enumerate(setlists)]


class TestBuildGroups:
    def test_setlist_feature_only_sees_shows_before_the_cutoff(self):
        # "old" was played before the first eligible cutoff, "new" only after.
        shows = _shows(date(2024, 1, 1), [{'old'}] * 3) + _shows(date(2024, 6, 1), [{'new'}] * 3)
        tracks = [_track(n) for n in ['old', 'new', 'c', 'd', 'e']]
        groups = build_groups('A', shows, tracks, {'old': 0.5})

        later = next(g for g in groups if g.cutoff == date(2024, 6, 1))
        assert [x[0] for x in later.X[:2]] == [1.0, 0.0]   # setlist: old, new
        assert later.y[:2] == [0.0, 1.0]

    def test_first_cutoff_has_no_setlist_history(self):
        shows = _shows(date(2024, 1, 1), [{'a'}] * 3)
        groups = build_groups('A', shows, [_track(n) for n in 'abcde'], {'a': 1.0})
        assert groups[0].cutoff == date(2024, 1, 1)
        assert not groups[0].has_setlist

    def test_tracks_released_after_cutoff_are_not_candidates(self):
        shows = _shows(date(2024, 1, 1), [{'a'}] * 3)
        tracks = [_track(n) for n in 'abcde'] + [_track('future', '2025-01-01')]
        groups = build_groups('A', shows, tracks, {'a': 1.0})
        assert all(len(g.y) == 5 for g in groups)

    def test_cutoffs_are_spaced_apart(self):
        shows = _shows(date(2024, 1, 1), [{'a'}] * 60, every_days=3)
        groups = build_groups('A', shows, [_track(n) for n in 'abcde'], {'a': 1.0})
        gaps = [(b.cutoff - a.cutoff).days for a, b in zip(groups, groups[1:])]
        assert len(groups) > 1 and min(gaps) >= 90

    def test_single_future_show_is_not_a_target(self):
        shows = _shows(date(2024, 1, 1), [{'a'}])
        assert build_groups('A', shows, [_track(n) for n in 'abcde'], {'a': 1.0}) == []

    def test_recency_is_measured_from_the_cutoff(self):
        shows = _shows(date(2024, 1, 1), [{'a'}] * 3)
        tracks = [_track('a', '2024-01-01')] + [_track(n) for n in 'bcde']
        g = build_groups('A', shows, tracks, {'a': 1.0})[0]
        assert g.X[0][FULL_FEATURES.index('recency')] == 1.0


class TestOptimiser:
    @pytest.mark.parametrize('obj', [RATIO, LISTNET], ids=lambda o: o.name)
    def test_gradient_matches_finite_differences(self, obj):
        rng = random.Random(1)
        g = _group([tuple(rng.random() for _ in range(3)) for _ in range(12)], [rng.random() for _ in range(12)])
        w = [0.5, 0.3, 0.2]
        _, grad = obj.loss_and_grad(w, g)
        eps = 1e-6

        def nudged(j, d):
            return [wi + d * (i == j) for i, wi in enumerate(w)]

        numeric = [(obj.loss(nudged(j, eps), g) - obj.loss(nudged(j, -eps), g)) / (2 * eps) for j in range(3)]
        assert grad == pytest.approx(numeric, rel=1e-4)

    def test_simplex_grid_rows_sum_to_one(self):
        grid = simplex_grid(3, 0.1)
        assert len(grid) == 66
        assert all(sum(w) == pytest.approx(1.0) for w in grid)

    def test_sgd_and_grid_recover_known_weights(self):
        # Targets generated by a known weighting; both fitters should find it.
        true_w = [0.6, 0.1, 0.3]
        rng = random.Random(0)
        groups = []
        for i in range(40):
            X = [tuple(rng.random() for _ in range(3)) for _ in range(20)]
            s = [sum(w * x for w, x in zip(true_w, row)) for row in X]
            groups.append(_group(X, [v / max(s) for v in s], artist=f'artist{i}'))

        assert fit_grid(groups) == pytest.approx(true_w, abs=0.011)
        assert fit_sgd(groups, epochs=60) == pytest.approx(true_w, abs=0.02)

    def test_listnet_sgd_matches_grid_on_ranking_data(self):
        # Songs are played in proportion to a softmax of a known weighting; the
        # two ListNet fitters should agree on the ratios to within the grid step.
        true_w = [6.0, 1.0, 3.0]
        rng = random.Random(0)
        groups = []
        for i in range(40):
            X = [tuple(rng.random() for _ in range(3)) for _ in range(20)]
            e = [2.718281828 ** sum(w * x for w, x in zip(true_w, row)) for row in X]
            groups.append(_group(X, [v / max(e) for v in e], artist=f'artist{i}'))

        sgd = normalized(fit_sgd(groups, LISTNET, epochs=60))
        assert sgd == pytest.approx(normalized(true_w), abs=0.03)
        assert sgd == pytest.approx(normalized(fit_grid(groups, LISTNET)), abs=0.05)

    def test_project_keeps_only_named_columns(self):
        g = _group([(0.1, 0.2, 0.3)], [1.0])
        assert project([g], ('lastfm', 'recency'))[0].X == [(0.2, 0.3)]


def _group(X, y, artist='A') -> Group:
    return Group(artist, date(2024, 1, 1), X, y, True)
